[workspace]
members = [
"src/token_contract",
"src/vault_contract",
"src/dripper",
"src/nft_contract",
"src/escrow_contract",
"src/escrow_contract/src/test/test_logic_contract",
"src/generic_proxy",
]

[benchmark]
token = "benchmarks/token_contract.benchmark.ts"
