[workspace]
members = [
"src/token_contract",
"src/vault_contract",
"src/vault_deployer",
"src/dripper",
"src/nft_contract",
"src/escrow_contract",
"src/escrow_contract/src/test/test_logic_contract",
"src/generic_proxy",
]

[benchmark]
token = "benchmarks/token_contract.benchmark.ts"
nft = "benchmarks/nft_contract.benchmark.ts"
vault = "benchmarks/vault_contract.benchmark.ts"
escrow = "benchmarks/escrow_contract.benchmark.ts"
logic = "benchmarks/logic_contract.benchmark.ts"
