[package]
name = "fee_payment_contract"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.82.3", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.82.3", directory = "noir-projects/aztec-nr/uint-note" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.82.3", directory = "noir-projects/aztec-nr/authwit" }
token = { path = "../token_contract" }
