[package]
name = "escrow_contract"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.1.0-rc.2", directory = "noir-projects/aztec-nr/aztec" }
serde = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.1.0-rc.2", directory = "noir-projects/noir-protocol-circuits/crates/serde" }
token = { path = "../token_contract" }
nft = { path = "../nft_contract" }
sha512 = { git = "https://github.com/noir-lang/sha512", tag = "master" } # TODO: pin to release tag/stable branch when available
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.9.2" }
