[package]
name = "token_contract"
type = "contract"
authors = [ "" ]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.86.0", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.86.0", directory = "noir-projects/aztec-nr/uint-note" }
balance_set = { path = "../libs/balance-set" }
bignum_field = { path = "../libs/bignum-field" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.86.0", directory = "noir-projects/aztec-nr/authwit" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.86.0", directory = "noir-projects/aztec-nr/compressed-string" }
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.7.1" }
