[package]
name = "token_contract"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
uint_note = { path = "../../../aztec-nr/uint-note" }
balance_set = { path = "../../../aztec-nr/balance-set" }
compressed_string = { path = "../../../aztec-nr/compressed-string" }
generic_proxy = { path = "../generic_proxy" }
