[package]
name = "vault_deployer"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
vault_contract = { path = "../vault_contract" }
token_contract = { path = "../token_contract" }
