[package]
name = "token_library"
authors = [""]
compiler_version = ">=1.0.0"
type = "lib"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.76.3", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { path = "../libs/uint-note" }
balance_set = { path = "../libs/balance-set" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.76.3", directory = "noir-projects/aztec-nr/compressed-string" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.76.3", directory = "noir-projects/aztec-nr/authwit" }
