name: Main Tests

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: defi-wonderland/aztec-ci-actions/.github/workflows/run-tests.yml@prerelease-v0.1.0 # TODO: rm `prerelease-` when aztec-ci-actions released
    secrets: inherit
