on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: write

jobs:
    tests:
      runs-on: ubuntu-latest
      timeout-minutes: 30
      env:
        AZTEC_VERSION: "0.85.0"
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
  
        - name: Install Aztec CLI
          run: |
            curl -s https://install.aztec.network > tmp.sh
            bash tmp.sh <<< yes "yes"
  
        - name: Update path
          run: echo "/home/runner/.aztec/bin" >> $GITHUB_PATH
  
        - name: Set Aztec version
          run: |
            VERSION=${AZTEC_VERSION} aztec-up
        
        - name: Start sandbox
          run: |
            aztec start --sandbox &

        - name: Install project dependencies
          run: yarn

        - name: Compile
          run: script -e -c "${AZTEC_NARGO:-aztec-nargo} compile"
        
        - name: Codegen
          run: script -e -c "aztec codegen target --outdir src/artifacts"
        
        - name: Benchmark
          uses: defi-wonderland/aztec-benchmark-diff@dev
          with:
            threshold: '2.0' 
            output_markdown_path: 'benchmark_diff.md' 

        - name: Comment diff
          uses: peter-evans/create-or-update-comment@v4
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body-file: benchmark_diff.md

        # - name: Start PXE
        #   run: |
        #     VERSION=${AZTEC_VERSION} aztec start --port 8081 --pxe --pxe.nodeUrl=http://localhost:8080/ --pxe.proverEnabled false &
        #
        # - name: Run nr tests
        #   run: |
        #     script -e -c "aztec test"
        #
        # - name: Run js tests
        #   run: script -e -c "BASE_PXE_URL=http://localhost NODE_NO_WARNINGS=1 node --experimental-vm-modules $(yarn bin jest) --no-cache --runInBand --config jest.integration.config.json"
