on:
    push:
      branches:
        - main
    pull_request:

jobs:
    setup-and-run:
      runs-on: ubuntu-latest
      timeout-minutes: 30
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
  
        - name: Install Aztec CLI
          run: |
            curl -s https://install.aztec.network > tmp.sh
            bash tmp.sh <<< yes "yes"
  
        - name: Update path
          run: echo "/home/runner/.aztec/bin" >> $GITHUB_PATH
  
        - name: Set Aztec version
          run: |
            VERSION=0.72.1 aztec-up
        
        - name: Start sandbox
          run: |
            docker compose -p sandbox -f ~/.aztec/docker-compose.sandbox.yml -f docker-compose.override.yml up &

        - name: Install project dependencies
          run: yarn
  
        - name: Compile
          run: script -e -c "${AZTEC_NARGO:-aztec-nargo} compile"
  
        - name: Codegen
          run: script -e -c "aztec codegen target --outdir src/artifacts"

        - name: Run js tests
          run: script -e -c "BASE_PXE_URL=http://localhost NODE_NO_WARNINGS=1 node --experimental-vm-modules $(yarn bin jest) --no-cache --runInBand --config jest.integration.config.json"
  
        - name: Run nr tests
          run: |
            script -e -c "aztec test"

