name: Update Benchmark Baseline

on:
  push:
    branches:
      - dev
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: update-baseline-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  baseline:
    uses: defi-wonderland/aztec-benchmark/.github/workflows/update-baseline.yml@5022f356e113c73ff42822f49186c56ee34b697d
    permissions:
      contents: read
      actions: write
    secrets: inherit
